version: '3.5'

services:


  hydrovis-worker:
    build: .
    environment:
      - MONGO_URL=mongodb
      - GRPC_UI_ADDRESS=
      - HTTP_UI_ADDRESS=
      - SECURE=True
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_STORAGE_ENDPOINT=http://minio:9000
    command: celery -A app.celery worker -Q visualization
    depends_on:
      - hydrovis
      - mongodb

  hydrovis:
    build: .
    environment:
      - MONGO_URL=mongodb
      - GRPC_UI_ADDRESS=
      - HTTP_UI_ADDRESS=
      - SECURE=True
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_STORAGE_ENDPOINT=http://minio:9000

    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.0.2
    container_name: mongodb
    ports:
      - "27017:27017"

