name: 'ci for docker'
on:
  pull_request:
    paths:
      - 'Dockerfile'
  

# Secrets:
#   DOCKERHUB_USERNAME - also used as the dockerhub repository url
#   DOCKERHUB_PASSWORD
 
env:
  HYDRO_SERVING_REPO: ${{ github.repository_owner }}/hydro-serving
  IMAGE: hydro-visualization # name of the built image
  REGISTRY: hydrosphere
  TAG: tech

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
              
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
          
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.0

      # Here a lot of tests
      - name: tests
        run: echo SUCCESS

  Build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
              
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
          
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.0

        # Update dependency
        # - name: Bump sdk
        #   run: |
        #     SDK_VERSION=$(curl -Ls https://pypi.org/pypi/hydrosdk/json | jq -r '.releases | keys[]' | sort -V | tail -n 1)
        #     echo $SDK_VERSION
        #     poetry add hydrosdk=$SDK_VERSION

      - name: Install dependencies
        run: poetry install

        #Bump service version
      - name: bump version
        if: github.events.inputs.version == ''
        run: poetry version ${{ github.event.inputs.bump }}

        #Set variables
      - name: Set VERSION variable
        run: echo VERSION=$(poetry version -s) >> $GITHUB_ENV
          
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildxtest-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
          cache-from: type=local,src=/tmp/.buildxtest-cache
          cache-to: type=local,dest=/tmp/.buildxtest-cache-new
          build-args: |
            GIT_HEAD_COMMIT=${{ github.sha }}
            GIT_CURRENT_BRANCH=${{ github.ref }}
      
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      - name: Move cache
        run: |
          rm -rf /tmp/.buildxtest-cache
          mv /tmp/.buildxtest-cache-new /tmp/.buildxtest-cache
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  

  Test_image:
    needs: [ "Build_image" ]
    runs-on: ubuntu-latest
    steps:
      - name: Test docker-compose in hydro-serving repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: master
          workflow: Test compose
          token: ${{ secrets.HYDRO_SERVING_TOKEN }}
          repo: ${{ env.HYDRO_SERVING_REPO }}
          inputs: '{"service_image_name":"${{ env.IMAGE }}", "registry_url":"${{ env.REGISTRY }}", "tag":"${{ env.TAG }}", "repository":"${{ github.repository }}", "pr_number":"${{ github.event.pull_request.number }}"}'